### ISSUE TITLE
Unclear instructions.

### ISSUE THREAD

**Issue by stephen-bailey-carta** [bluemoosegoose/Build-a-Custom-Dock#1]
Hey Blue, thanks a ton for the guide. I have a bit of an issue with one line, though: 'Use Jamf Composer to create a .pkg of that script and name it “BuildtheDockScript.pkg” '

It's not obvious if one is to place the script file in the pkg (and where it needs to go) or if one should add the script contents to the script section of composer. It would be great if there was a little clarification. 

Thanks a ton again for the script and guide.

**Comment by bluemoosegoose** [comment]
That's a good catch. I'll update the guide to make it more clear. You want to put "BuildtheDock.sh" in the location where it is going to saved on each client machine. This script will get placed in this location and remain there. I chose to put it in "Library/Scripts" and step 14 shows the launchagent calling the script at that location. You'll also probably want to make sure you give it 775 permissions when you're creating the PKG in Composer. 

The reason the script is called via launchagent versus a policy that runs the script is that Jamf runs scripts as root, and we need it to be run as the current user, otherwise it won't affect the current user's dock.

**Comment by Bilal-Mohamed** [comment]
Hey Blue,
Have looked at deploying this in my environment with edits. Note edits were not made to the launch ageny script yet in testing I get this error as the script result on the policy completion.

Script result: currentuser-variable = bilal.mohamed
Finished unloading launchagent
Load failed: 5: Input/output error
Try running `launchctl bootstrap` as root for richer errors.
Finished loading launchagent

Any idea,
Bilal
